version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: democache
    ports:
      - "3306:3306"

  app:
    image: node:20
    command: sh -c "ls && yarn && npx sequelize db:migrate && yarn dev"
    environment:
      DATABASE_URL: mysql://root:password@db:3306/democache
    depends_on:
      - db
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_HOST: db
